#Integers
#Addition
a = '1'
b = '7'
c = int(a) + int(b)
print(f"The addition of '{a}' and '{b}' is '{c}'") 

c = "The addition of '{}' and '{}' is '{}'".format(a, b, int(a) + int(b))
print(c)

#Subtraction
c = int(a) - int(b)
print(f"The subtraction of '{a}' and '{b}' is '{c}'")

c = "The subtraction of '{}' and '{}' is '{}'".format(a, b, int(a) - int(b))
print(c)

#Multiplication
c = int(a) * int(b)
print(f"The multiplication of '{a}' and '{b}' is '{c}'")

c = "The multiplication of '{}' and '{}' is '{}'".format(a, b, int(a) * int(b))
print(c)

#Division
c = int(a) / int(b)
print(f"The division of '{a}' and '{b}' is '{c}'")

c = "The division of '{}' and '{}' is '{}'".format(a, b, int(a) / int(b))
print(c)

#Modulo
c = int(a) % int(b)
print(f"The modulo of '{a}' and '{b}' is '{c}'")

c = "The modulo of '{}' and '{}' is '{}'".format(a, b, int(a) % int(b))
print(c)

#Exponent
c = int(a) ** int(b)
print(f"The exponent of '{a}' and '{b}' is '{c}'")

c = "The exponent of '{}' and '{}' is '{}'".format(a, b, int(a) ** int(b))
print(c)

#FloorDivision
c = int(a) // int(b)
print(f"The floordivision of '{a}' and '{b}' is '{c}'")

c = "The floordivision of '{}' and '{}' is '{}'".format(a, b, int(a) // int(b))
print(c)

#Negation
c = -(int(a)) + -(int(b)) 
print(f"The negation of '{a}' and '{b}' is '{c}'")

c = "The negation of '{}' and '{}' is '{}'".format(a, b, -(int(a)) + -(int(b)))
print(c)

#-------------------------------------------------------------------------------------

#Floats
#Addition
a = '2.7'
b = '7.3'
c = float(a) + float(b)
print(f"The addition of '{a}' and '{b}' is '{c}'") 

c = "The addition of '{}' and '{}' is '{}'".format(a, b, float(a) + float(b))
print(c)

#Subtraction
c = float(a) - float(b)
print(f"The subtraction of '{a}' and '{b}' is '{c}'")

c = "The subtraction of '{}' and '{}' is '{}'".format(a, b, float(a) - float(b))
print(c)

#Multiplication
c = float(a) * float(b)
print(f"The multiplication of '{a}' and '{b}' is '{c}'")

c = "The multiplication of '{}' and '{}' is '{}'".format(a, b, float(a) * float(b))
print(c)

#Division
c = float(a) / float(b)
print(f"The division of '{a}' and '{b}' is '{c}'")

c = "The division of '{}' and '{}' is '{}'".format(a, b, float(a) / float(b))
print(c)

#Modulo
c = float(a) % float(b)
print(f"The modulo of '{a}' and '{b}' is '{c}'")

c = "The modulo of '{}' and '{}' is '{}'".format(a, b, float(a) % float(b))
print(c)

#Exponent
c = float(a) ** float(b)
print(f"The exponent of '{a}' and '{b}' is '{c}'")

c = "The exponent of '{}' and '{}' is '{}'".format(a, b, float(a) ** float(b))
print(c)

#FloorDivision
c = float(a) // float(b)
print(f"The floordivision of '{a}' and '{b}' is '{c}'")

c = "The floordivision of '{}' and '{}' is '{}'".format(a, b, float(a) // float(b))
print(c)

#Negation
c = -(float(a)) + -(float(b)) 
print(f"The negation of '{a}' and '{b}' is '{c}'")

c = "The negation of '{}' and '{}' is '{}'".format(a, b, -(float(a)) + -(float(b)))
print(c)



































